### ISSUE TITLE
Need Binary Response Content

### ISSUE THREAD

**Issue by tototas** [deedy5/pyreqwest_impersonate#1]
Hello.
I think you need to add the rest of the properties of the answer.
"response.content" - https://requests.readthedocs.io/en/latest/user/quickstart/#binary-response-content

it is impossible to obtain raw data. For example, pictures
 =(( text only.

Thanks!

**Comment by deedy5** [comment]
Hello. 
Thank you for your interest.

I am already working on it and a new release is coming soon.

**Comment by deedy5** [comment]
v0.2.0
