### ISSUE TITLE
wheel for android

### ISSUE THREAD

**Issue by krolaper** [deedy5/pyreqwest_impersonate#10]
can you make a wheel for android?
logcat:
```
pyreqwest_impersonate/pyreqwest_impersonate.abi3.so" is for EM_X86_64 (62) instead of EM_AARCH64 (183)
```
I achieved good results on PC, so I still really need to get a release for arm64

**Comment by deedy5** [comment]
How do you set it up?
https://pypi.org/project/pyreqwest-impersonate/#files

EM_AARCH64 - `pyreqwest_impersonate-0.4.1-cp38-abi3-manylinux_2_28_aarch64.whl`

**Comment by deedy5** [comment]
https://github.com/Android-for-Python/Android-for-Python-Users#em_x86_64-instead-of-em_aarch64

**Comment by krolaper** [comment]
@deedy5 I'll explain. `pyreqwest_impersonate-0.4.1-cp38-abi3-manylinux_2_28_aarch64.whl` are designed more for working in `termux`. And I have my own separately packaged application (.apk file). The problem arises because of how this binary file was packaged. Your competitors `curl-cffi` have the same problem, but their situation is more complicated.

The fact that you are posting a link to the description of the error is something I have studied for a long time and this is not the first time I have encountered this. Now I’m trying to make the recipe myself, but there’s little chance I’ll succeed. That's why I wrote to you.
So that you better understand the problem, do a test with packaging for android and test it.
Thank you for your understanding, I hope you can resolve this issue.

**Comment by krolaper** [comment]
https://github.com/kivy/python-for-android/issues/3012 A working recipe, as you understand.
