### ISSUE TITLE
TypeError: argument 'data': 'list' object cannot be converted to 'PyString'

### ISSUE THREAD

**Issue by farukekim** [deedy5/pyreqwest_impersonate#12]
When i try to post json data like that ( a list in json ), i am getting TypeError: argument 'data': 'list' object cannot be converted to 'PyString' error.

Code Example: 
`data = {
            "device_id": "123",
            "auth": ["auth_options", "sms_auth_v2", "two_factor_auth"]
        }`

`resp = client.post(url="https://httpbin.org/anything", data=data)`

**Comment by farukekim** [comment]
Also getting same error while trying to post protobuf data ( bytearray data )
TypeError: argument 'data': 'bytearray' object cannot be converted to 'PyString'

**Comment by deedy5** [comment]
Fixed in v0.4.3

**Comment by deedy5** [comment]
The `json` parameter also became available

**Comment by farukekim** [comment]
Even using json parameter, the module is not sending the json data as json, its sending as data, could you please check it again?

Let me explain it : 

Used python's requests module while sending json data. The response is showing the data as json.
{
  "args": {}, 
  "data": "{\"device_id\": \"2f7459af-cd5f-4b44-92cf-cb251fef6df2\", \"auth\": [\"auth_options\", \"sms_auth_v2\", \"two_factor_auth\"]}", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7", 
    "Accept-Encoding": "gzip, deflate, br", 
    "Accept-Language": "en;q=0.8,en-GB;q=0.7,en-US;q=0.6", 
    "Cache-Control": "max-age=0", 
    "Content-Length": "113", 
    "Dnt": "1", 
    "Host": "httpbin.org", 
    "Sec-Ch-Ua": "\"Google Chrome\";v=\"123\", \"Not:A-Brand\";v=\"8\", \"Chromium\";v=\"123\"", 
    "Sec-Ch-Ua-Mobile": "?0", 
    "Sec-Ch-Ua-Platform": "\"macOS\"", 
    "Sec-Fetch-Dest": "document", 
    "Sec-Fetch-Mode": "navigate", 
    "Sec-Fetch-Site": "none", 
    "Sec-Fetch-User": "?1", 
    "Upgrade-Insecure-Requests": "1", 
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36", 
    "X-Amzn-Trace-Id": "Root=1-663f5750-643d187f36b8d09f43827da3"
  }, 
  "json": {
    "auth": [
      "auth_options", 
      "sms_auth_v2", 
      "two_factor_auth"
    ], 
    "device_id": "2f7459af-cd5f-4b44-92cf-cb251fef6df2"
  }, 
  "method": "POST", 
  "origin": "", 
  "url": "https://httpbin.org/anything"
}

But with tthe pyreqwest module its still sending as data, not as a json : 

{
  "args": {}, 
  "data": "{'device_id': '2f7459af-cd5f-4b44-92cf-cb251fef6df2', 'auth': ['auth_options', 'sms_auth_v2', 'two_factor_auth']}", 
  "files": {}, 
  "form": {}, 
  "headers": {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7", 
    "Accept-Encoding": "gzip, deflate, br", 
    "Accept-Language": "en;q=0.8,en-GB;q=0.7,en-US;q=0.6", 
    "Cache-Control": "max-age=0", 
    "Content-Length": "113", 
    "Content-Type": "application/json", 
    "Dnt": "1", 
    "Host": "httpbin.org", 
    "Sec-Ch-Ua": "\"Google Chrome\";v=\"123\", \"Not:A-Brand\";v=\"8\", \"Chromium\";v=\"123\"", 
    "Sec-Ch-Ua-Mobile": "?0", 
    "Sec-Ch-Ua-Platform": "\"macOS\"", 
    "Sec-Fetch-Dest": "document", 
    "Sec-Fetch-Mode": "navigate", 
    "Sec-Fetch-Site": "none", 
    "Sec-Fetch-User": "?1", 
    "Upgrade-Insecure-Requests": "1", 
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36", 
    "X-Amzn-Trace-Id": "Root=1-663f5823-58b0e0ef22e110327c234e9a"
  }, 
  "json": null, 
  "method": "POST", 
  "origin": "", 
  "url": "https://httpbin.org/anything"
}

As you see the module sent the request data as data not as json.

**Comment by deedy5** [comment]
@farukekim Try v0.4.4
