### ISSUE TITLE
Allow sending files better

### ISSUE THREAD

**Issue by AnasBoujamaa** [deedy5/pyreqwest_impersonate#18]
Hey! I noticed that you fixed some bugs sending files and now it's working, but there's still a problem. Most websites require the files to contain a specific mimetype and a filename. For that reason libraries like requests allow you to specify the name of the file and a tuple with the filename (with the extension, like .png), the file content and the mimetype, but right now with your repo I can only specify the content. The mimetype is always application/octet-stream and I think think that the filename is not sent. It would be nice to add that option too!

Edit: I saw that the library curl_cffi (https://github.com/yifeikong/curl_cffi) allows you to set a multipart object with every setting (https://github.com/yifeikong/curl_cffi/blob/v0.7.0b6/examples/upload.py) like the name of the part, the name of the file, the content type and the content because it's easier than managing files as requests do.

**Comment by deedy5** [comment]
I have plans to do file uploads with different parameters, but it's not that easy and I need time. 
Please don't create an issue without a specific problem. 
Also attach the code so I can reproduce the issue quickly. 
Thanks for your understanding.
