### ISSUE TITLE
When sending files data is not sending

### ISSUE THREAD

**Issue by AnasBoujamaa** [deedy5/pyreqwest_impersonate#19]
When sending files, even using the new package where you fixed some bugs, neither the data nor the JSON data is sending. I confirmed this with https://httpbin.org/anything

**Comment by deedy5** [comment]
I don't understand the question. 
Choose one thing when sending data in the request: `content` or `data` or `json` or `files`.

**Comment by AnasBoujamaa** [comment]
Isn't it possible to send some of them at the same time? Other libraries like requests allow that.
